'use client';

import { motion } from 'framer-motion';
import { Download, Smartphone, Rocket, Lock, PartyPopper } from 'lucide-react';
import { useState, useEffect } from 'react';
import { ScreenData } from './ScreenCard';

interface Props {
  screens: ScreenData[];
  appName: string;
  primaryColor: string;
}

export default function StepBuild({ screens, appName, primaryColor }: Props) {
  const [downloading, setDownloading] = useState(false);
  const [showConfetti, setShowConfetti] = useState(true);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    if (showConfetti) {
      const t = setTimeout(() => setShowConfetti(false), 4000);
      return () => clearTimeout(t);
    }
  }, [showConfetti]);

  const downloadZip = async () => {
    setDownloading(true);
    setProgress(0);

    // Simulate progress
    const interval = setInterval(() => {
      setProgress(p => Math.min(p + Math.random() * 15, 90));
    }, 200);

    try {
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();

      const safeName = appName.replace(/[^a-zA-Z0-9-_]/g, '').toLowerCase() || 'my-app';

      // app.json
      zip.file('app.json', JSON.stringify({
        expo: {
          name: appName || 'My App',
          slug: safeName,
          version: '1.0.0',
          orientation: 'portrait',
          icon: './assets/icon.png',
          userInterfaceStyle: 'automatic',
          splash: { image: './assets/splash.png', resizeMode: 'contain', backgroundColor: primaryColor },
          ios: { supportsTablet: true },
          android: { adaptiveIcon: { foregroundImage: './assets/adaptive-icon.png', backgroundColor: primaryColor }, package: `com.${safeName}.app` },
          web: { favicon: './assets/favicon.png' },
        },
      }, null, 2));

      // package.json
      zip.file('package.json', JSON.stringify({
        name: safeName,
        version: '1.0.0',
        main: 'node_modules/expo/AppEntry.js',
        scripts: { start: 'expo start', android: 'expo start --android', ios: 'expo start --ios', web: 'expo start --web' },
        dependencies: {
          expo: '~50.0.0',
          'expo-status-bar': '~1.11.1',
          react: '18.2.0',
          'react-native': '0.73.4',
          '@react-navigation/native': '^6.1.9',
          '@react-navigation/native-stack': '^6.9.17',
          '@react-navigation/bottom-tabs': '^6.5.11',
          'react-native-screens': '~3.29.0',
          'react-native-safe-area-context': '4.8.2',
          'react-native-paper': '^5.12.3',
          'react-native-vector-icons': '^10.0.3',
        },
        devDependencies: { '@babel/core': '^7.20.0', '@types/react': '~18.2.45', typescript: '^5.1.3' },
        private: true,
      }, null, 2));

      // babel.config.js
      zip.file('babel.config.js', `module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
`);

      // tsconfig.json
      zip.file('tsconfig.json', JSON.stringify({
        extends: 'expo/tsconfig.base',
        compilerOptions: { strict: true },
      }, null, 2));

      // Generate screen files
      const screenFiles = screens.map(s => {
        const fileName = s.name.replace(/[^a-zA-Z0-9]/g, '') + 'Screen';
        return { fileName, code: s.code || generateDefaultScreenCode(s.name, primaryColor) };
      });

      const screensDir = zip.folder('screens')!;
      screenFiles.forEach(sf => {
        screensDir.file(`${sf.fileName}.tsx`, sf.code);
      });

      // App.tsx
      const imports = screenFiles.map(sf => `import ${sf.fileName} from './screens/${sf.fileName}';`).join('\n');
      const tabScreens = screenFiles.map(sf => `        <Tab.Screen name="${sf.fileName.replace('Screen', '')}" component={${sf.fileName}} />`).join('\n');

      zip.file('App.tsx', `import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { StatusBar } from 'expo-status-bar';
import { PaperProvider, MD3LightTheme } from 'react-native-paper';

${imports}

const Tab = createBottomTabNavigator();

const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '${primaryColor}',
  },
};

export default function App() {
  return (
    <PaperProvider theme={theme}>
      <NavigationContainer>
        <Tab.Navigator screenOptions={{ headerStyle: { backgroundColor: '${primaryColor}' }, headerTintColor: '#fff' }}>
${tabScreens}
        </Tab.Navigator>
      </NavigationContainer>
      <StatusBar style="auto" />
    </PaperProvider>
  );
}
`);

      // assets folder placeholder
      const assets = zip.folder('assets')!;
      assets.file('.gitkeep', '');

      // README
      zip.file('README.md', `# ${appName || 'My App'}

Generated by [SheruTools AI App Builder](https://sherutools.com/app-builder)

## Getting Started

\`\`\`bash
npm install
npx expo start
\`\`\`

Scan the QR code with Expo Go on your phone, or press \`a\` for Android emulator.

## Screens
${screens.map((s, i) => `${i + 1}. ${s.name}`).join('\n')}

## Build APK
\`\`\`bash
npx eas build --platform android --profile preview
\`\`\`
`);

      clearInterval(interval);
      setProgress(100);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${safeName}-expo-project.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="space-y-8"
    >
      {/* Confetti */}
      {showConfetti && (
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0 }}
          className="text-center"
        >
          <div className="text-6xl mb-2">🎉</div>
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Your App is Ready!</h2>
          <p className="text-slate-500 dark:text-slate-400 mt-1">{screens.length} screens generated for &ldquo;{appName}&rdquo;</p>
        </motion.div>
      )}

      {/* Download ZIP */}
      <div className="p-6 rounded-2xl border border-slate-200 dark:border-white/10 bg-white/50 dark:bg-white/[0.02] space-y-4">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center">
            <Download className="w-6 h-6 text-blue-500" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white">Download Expo Project</h3>
            <p className="text-sm text-slate-500 dark:text-slate-400">Complete project ZIP — run with npx expo start</p>
          </div>
        </div>

        {downloading && (
          <div className="w-full h-2 rounded-full bg-slate-200 dark:bg-white/10 overflow-hidden">
            <motion.div
              className="h-full bg-gradient-to-r from-blue-500 to-purple-500 rounded-full"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
            />
          </div>
        )}

        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={downloadZip}
          disabled={downloading}
          className="w-full py-3 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 text-white font-bold shadow-lg disabled:opacity-50 flex items-center justify-center gap-2"
        >
          <Download className="w-5 h-5" />
          {downloading ? 'Generating ZIP...' : 'Download ZIP'}
        </motion.button>
      </div>

      {/* APK Build - Coming Soon */}
      <div className="p-6 rounded-2xl border border-dashed border-slate-300 dark:border-white/10 bg-slate-50/50 dark:bg-white/[0.01] space-y-4 relative overflow-hidden">
        <div className="absolute top-3 right-3 px-3 py-1 rounded-full bg-amber-500/10 text-amber-500 text-xs font-bold">Coming Soon</div>
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-green-500/10 flex items-center justify-center">
            <Smartphone className="w-6 h-6 text-green-500" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white">Build Android APK</h3>
            <p className="text-sm text-slate-500 dark:text-slate-400">We&apos;ll compile a real APK you can install — $4.99/build or free with Pro</p>
          </div>
        </div>
        <button disabled className="w-full py-3 rounded-xl bg-slate-200 dark:bg-white/5 text-slate-400 font-bold cursor-not-allowed flex items-center justify-center gap-2">
          <Rocket className="w-5 h-5" /> Build APK — Coming Soon
        </button>
      </div>

      {/* Pro upsell */}
      <div className="p-6 rounded-2xl bg-gradient-to-br from-purple-500/10 via-blue-500/10 to-pink-500/10 border border-purple-500/20 space-y-3">
        <div className="flex items-center gap-2">
          <Lock className="w-5 h-5 text-purple-400" />
          <h3 className="font-bold text-slate-900 dark:text-white">Unlock Pro</h3>
        </div>
        <ul className="text-sm text-slate-600 dark:text-slate-300 space-y-1">
          <li>✨ Unlimited app generations</li>
          <li>📱 8+ screens per app</li>
          <li>🔨 APK build included</li>
          <li>🎨 Custom app icons</li>
          <li>🔔 Push notifications config</li>
        </ul>
        <button className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-pink-600 text-white font-bold text-sm shadow-lg">
          Upgrade — $19.99/mo
        </button>
      </div>
    </motion.div>
  );
}

function generateDefaultScreenCode(name: string, color: string): string {
  const safeName = name.replace(/[^a-zA-Z0-9]/g, '');
  return `import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';

export default function ${safeName}Screen() {
  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>${name}</Text>
      </View>
      <View style={styles.content}>
        <Text style={styles.text}>Welcome to ${name}</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  header: { padding: 20, backgroundColor: '${color}' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#fff' },
  content: { padding: 20 },
  text: { fontSize: 16, color: '#333' },
});
`;
}
