import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Free AI Email Writer - Generate Professional Emails | SheruTools',
  description:
    'Write professional emails instantly with AI. Choose purpose, tone, and key points. Generate perfect emails in seconds. Free, no sign-up required.',
  keywords: ['ai email writer', 'ai email generator', 'write email with ai', 'professional email writer free'],
  alternates: { canonical: 'https://sherutools.com/ai-email-writer' },
  openGraph: {
    title: 'Free AI Email Writer - Generate Professional Emails | SheruTools',
    description:
      'Write professional emails instantly with AI. Choose purpose, tone, and key points. Generate perfect emails in seconds. Free, no sign-up required.',
    url: 'https://sherutools.com/ai-email-writer',
  }
};

const jsonLd = [
  {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://sherutools.com' },
      { '@type': 'ListItem', position: 2, name: 'Free AI Email Writer', item: 'https://sherutools.com/ai-email-writer' },
    ],
  },
  {
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'SheruTools AI Email Writer',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
  {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
    {
      '@type': 'Question',
      name: "Is the AI Email Writer free?",
      acceptedAnswer: { '@type': 'Answer', text: "Yes! Generate professional emails completely free with no sign-up required. Free users get a daily generation limit." },
    },
    {
      '@type': 'Question',
      name: "What types of emails can I generate?",
      acceptedAnswer: { '@type': 'Answer', text: "You can generate business emails, follow-ups, cold outreach, thank you notes, apologies, meeting requests, and many more professional email types." },
    },
    {
      '@type': 'Question',
      name: "Can I customize the tone of generated emails?",
      acceptedAnswer: { '@type': 'Answer', text: "Yes, choose from multiple tones including professional, friendly, formal, casual, and persuasive to match your communication style." },
    },
    {
      '@type': 'Question',
      name: "Are the generated emails unique?",
      acceptedAnswer: { '@type': 'Answer', text: "Yes, each email is uniquely generated by AI based on your specific inputs, purpose, and key points." },
    }
    ],
  },
];

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      {children}
    </>
  );
}
